name: churrascos_dulces_app
description: Sistema de gestión para churrascos y dulces típicos guatemaltecos
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI y Material Design
  cupertino_icons: ^1.0.2
  
  # HTTP y APIs
  http: ^1.1.0
  
  # Estado y arquitectura
  flutter_riverpod: ^2.4.9
  
  # Gráficos y charts
  fl_chart: ^0.64.0
  
  # Fechas y tiempo - REMOVEMOS intl específico, usamos el del SDK
  # intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true